# Ruta de la API
#GET http://localhost:3000/api

# Ruta para rutas que no existen
# GET http://localhost:3000/api/* 

# Ruta para obtener todos los usuarios (protegida)
# GET http://localhost:3000/api/usuarios
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWlteXRhdGlhYW5hcGludG9AZ21haWwuY29tIn0.UTLeP0gYWqsvwrHva3QXdCr0xtxzKesw_NSmFcPhXug

# # Ruta para obtener un usuario por su id (protegida)
# GET http://localhost:3000/api/usuarios/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWlteXRhdGlhYW5hcGludG9AZ21haWwuY29tIn0.UTLeP0gYWqsvwrHva3QXdCr0xtxzKesw_NSmFcPhXug

# # Ruta para obtener un usuario por su documento (protegida)
# GET http://localhost:3000/api/usuarios/documento/1053872476
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWlteXRhdGlhYW5hcGludG9AZ21haWwuY29tIn0.UTLeP0gYWqsvwrHva3QXdCr0xtxzKesw_NSmFcPhXug

# # Ruta para crear un usuario (registro)
 POST http://localhost:3000/api/auth/register
 Content-Type: application/json

 {
    "nombre": "Jeimy",
    "apellido": "Pinto",
    "documento": "000000000",
    "telefono": "3058122481",
     "email": "jeimy@example.com",
     "contrasena": "password123",
     "CreateAt": "2021-08-10",
     "UpdateAt": "2021-08-10",
 }

# Ruta para iniciar sesión
# POST http://localhost:3000/api/auth/login
# Content-Type: application/json

# {
#     "email": "willy@gmail.com",
#     "contrasena": "1234"
# }

# # Ruta para cerrar sesión (protegida)
# POST http://localhost:3000/api/auth/logout
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWlteXRhdGlhYW5hcGludG9AZ21haWwuY29tIn0.UTLeP0gYWqsvwrHva3QXdCr0xtxzKesw_NSmFcPhXug