# Ruta de la API
# GET http://localhost:3000/api

# Ruta para rutas que no existen
# GET http://localhost:3000/api/* 

# Ruta para obtener todos los usuarios
# GET http://localhost:3000/api/usuarios

# Ruta para obtener un usuario por su id
# GET http://localhost:3000/api/usuarios/1

# Ruta para obtener un usuario por su documento
# GET http://localhost:3000/api/usuarios/documento/1053872476

# Ruta para crear un usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "Jeimy",
    "apellido": "Pinto",
    "documento": "1053872476",
    "telefono": "3058122481",
    "email": "jeimy@gmail.com",
    "contrasena": "Prueba123#",
    "estado": "activa"
}

# Ruta para actualizar un usuario
# PUT http://localhost:3000/api/usuarios/1 HTTP/1.1
# Content-Type: application/json

# {
#     "id": 1,
#     "nombre": "Jeimy",
#     "apellido": "Pinto",
#     "documento": "1053872476",
#     "telefono": "3058122481",
#     "email": "jeimytatianapinto@gmail.com",
#     "contrasena": "Bienestarjeimy1399.",
#     "estado": "activa"
# }

# Ruta para eliminar un usuario
DELETE http://localhost:3000/api/usuarios/3
