import "./styles/globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";

export const metadata = {
  title: "Portal de Bienestar al Aprendiz",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" href="/images/favicon.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="{`${monserrate.className} antialiase`} bg-blanco">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}